name: Scrape Points Table

on:
  schedule:
    - cron: '30 20 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm i
      - name: Scrape Points Table
        run: node scrape.js
      - name: Env Setup
        env:
          MONGODB_URI: ${{secrets.MONGODB_URI}}